src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", length=4)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     * @Assert\NotBlank(message="Please enter the task name.")
     * @Assert\Length(min = 3, minMessage = "Task name should be at least 3 characters.",
     * max = 128, maxMessage = "Task name must be shorter than 128 characters.",)
     */
    private $task_name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Please enter a description for the task.")
     */
    private $task_description;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Please select the status.")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $add_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $completed_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTaskName(): ?string
    {
        return $this->task_name;
    }

    public function setTaskName(string $task_name): self
    {
        $this->task_name = $task_name;

        return $this;
    }

    public function getTaskDescription(): ?string
    {
        return $this->task_description;
    }

    public function setTaskDescription(string $task_description): self
    {
        $this->task_description = $task_description;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAddDate(): ?\DateTimeInterface
    {
        return $this->add_date;
    }

    public function setAddDate(\DateTimeInterface $add_date): self
    {
        $this->add_date = $add_date;

        return $this;
    }

    public function getCompletedDate(): ?\DateTimeInterface
    {
        return $this->completed_date;
    }

    public function setCompletedDate(\DateTimeInterface $completed_date): self
    {
        $this->completed_date = $completed_date;

        return $this;
    }

    private $img;
    
    public function getImg()
    {
        $filesystem = new Filesystem();
        if($filesystem->exists('assets/img/tasks/' . $this->id . '.jpg')){
        return '/assets/img/tasks/'.$this->id . '.jpg';
        }else{
            return '/build/missing.png';
        }
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $img
     */
    public function setImg(UploadedFile $img = null)
    {
        // $this->img = $img;
    }

}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="home">
		<img src="{{ asset('build/home.jpg') }}" alt="Home">
			<h1>Tasks scheduler</h1>
	</div>
{% endblock %}

templates/pages/statuses.html.twig
{% extends 'base.html.twig' %}

			{% block title %}Tasks scheduler - Statuses
			{% endblock %}

{% block body %}

	<div class='blur' data-controller="status" data-action="click->status#close"></div>

	{% if app.user %}
		<div class="row">
			<div class="col-lg-8">
				<button type="button" class="btn bg-custom2 mb-2 col-lg-12 d-inline" data-controller="status" data-action="click->status#editor">
					Add status
				</button>
			</div>
			<div class="col-sm">
			{% endif %}
			{% set arrPaths = app.request.pathinfo|split('/') %}
			<select class="form-control bg-custom2 col-lg-12 d-inline" name="sort" onchange="location = this.value;">
				<option value='#' {% if arrPaths[2] ?? 0 == 0 %} selected {% endif %}>Sort by</option>
				{% for key,choice in sort %}
					<option {% if arrPaths[2] ?? 0 == key %} selected {% endif %} value={{ base_url ~ '/' ~ key }}>{{ choice.1.name }}</option>
				{% endfor %}
			</select>
			{% if app.user %}
			</div>
		</div>
		<div class='adminBox' style="max-width: 500px;">
			{{form_start(addstatusForm)}}
			<div class='box1'>
				{{ form_row(addstatusForm.name, { label: 'Status name'})  }}
			</div>
			<div class='error'></div>
			{{ form_row(addstatusForm.save) }}
			{{form_end(addstatusForm)}}
		</div>

	{% endif %}

	<div class="container-fluid">
		<div class="row">
			{% for status in statuses %}

				<div class='status col-xl-12 bg-custom bg-gradient' tabindex='0' data-controller="status" data-action="click->status#view">

					{% if app.user %}
						<div class='options' tabindex='0'>
							<i class="fa fa-angle-down" aria-hidden="true"></i>
							<p class='edit' id='{{ status.id }}' data-controller="status" data-action="click->status#get">Edit</p>
							<p class='delete' id='{{ status.id }}' data-controller="status" data-action="click->status#delete">Delete</p>
						</div>
					{% endif %}

					<h1>{{ status.name }}</h1>
					<div class='error' id='error_{{ status.id }}'></div>

					<div class='tasks'>
						<h1>Tasks</h1>

						{% for task in status.tasks %}
							<p>{{ task.taskName }}
								(ID:
								{{ task.id }})</p>
						{% endfor %}


						{% if status.tasks|length < 1 %}
					<div class='error'>There are no tasks for this status.</div>
						{% endif %}

					</div>

				</div>
			{% endfor %}
		</div>
	{% endblock %}

templates/pages/tasks.html.twig
{% extends 'base.html.twig' %}

			{% block title %}Tasks scheduler - Tasks
			{% endblock %}

{% block body %}

	<div class='blur' data-controller="task" data-action="click->task#close"></div>

	<div class="row">
		{% if app.user %}
			<div class="col-lg-6">
				<button type="button" class="btn bg-custom2 mb-2 col-lg-12 d-inline" data-controller="task" data-action="click->task#editor">
					Add task
				</button>
			</div>
		{% endif %}
		<div class="col-sm">

			{% set arrPaths = app.request.pathinfo|split('/') %}

			<select name="filter" class="form-control bg-custom2 col-lg-12 d-inline" onchange="location = this.value;">
				<option value='#'>Filter by</option>
			<option {% if arrPaths[3] ?? 0 == 0 %} selected {% endif %} value={{ base_url ~ '/' ~ arrPaths[2] ?? 'id_task' ~ '/0'}}>All statuses</option>
				{% set arrayDublicates = [] %}
				{% for choice in tasks_objects %}
					{% if choice.status.name not in arrayDublicates %}
						{% set arrayDublicates = arrayDublicates|merge([choice.status.name]) %}
						<option {% if arrPaths[3] ?? 0 == choice.status.name %} selected {% endif %} value={{ base_url ~ '/' ~ arrPaths[2] ?? '0' ~ '/' ~ choice.status.id}}>{{ choice.status.name }}</option>
					{% endif %}
				{% endfor %}
			</select>
		</div>

		<div class="col-sm">
			<select name="sort" class="form-control bg-custom2 col-lg-12 d-inline" onchange="location = this.value;">
				<option value='#' {% if arrPaths[2] ?? 0 == 0 %} selected {% endif %}>Sort by</option>
				{% for key,choice in sort %}
					<option {% if arrPaths[2] ?? 'id_task' == key %} selected {% endif %} value={{ base_url ~ '/' ~ key ~ '/' ~ arrPaths[3] ?? ''}}>{{ choice.1.name }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	{% if app.user %}
		<div class='adminBox' style="position: absolute; max-width: 1200px;">
			{{form_start(addtaskForm)}}
			<div class='row'>
				<div class="col-sm-2" style="min-width:250px !important; max-width:250px; min-height:150px;">
					<div class='uploadImg'>
						<img src="{{ asset('build/missing.png') }}" alt='task'>
						{{ form_row(addtaskForm.img, { label: ' '}) }}
					</div>
				</div>
				<div class="col-sm">
					{{ form_row(addtaskForm.task_name) }}
					{{ form_row(addtaskForm.status) }}
					{{ form_row(addtaskForm.completed_date) }}
				</div>
			</div>
			{{ form_row(addtaskForm.task_description, { label: ' '}) }}
			<div class='error'></div>
			{{ form_row(addtaskForm.save) }}
			{{form_end(addtaskForm)}}
		</div>

	{% endif %}
	<div class="row">
		{% for task in tasks %}
			<div class="col-lg-6">
				<div class='task col-lg-12 bg-custom bg-gradient' data-controller="task" data-action="click->task#view" tabindex='0'>
					{% if app.user %}
						<div class='options' tabindex='0'>
							<i class="fa fa-angle-down" aria-hidden="true"></i>
							<p class='edit' id='{{ task.id }}' data-controller="task" data-action="click->task#get">Edit</p>
							<p class='delete' id='{{ task.id }}' data-controller="task" data-action="click->task#delete">Delete</p>
						</div>
					{% endif %}
					<div class="row">
						<div class="col-md-push position-relative" style="min-width:200px; min-height: 150px;">
							<img src="{{ task.img }}" alt='task' data-controller="task" data-action="click->task#img">
						</div>
						<div class="col-md-push" style="margin-left: 10px;">
							<h1>{{ task.taskName }}</h1>
							<p>Status: {{ task.status.name }}</p>
							<p>Add date: {{ task.addDate|date('Y-m-d') }}</p>
							{% if task.completedDate != null %}
							<p>Completed date: {{ task.completedDate|date('Y-m-d')  }}</p>
							{% endif %}
							<p>ID:
								{{ task.id }}</p>
						</div>
					</div>
					<div class='about'>
						{{ task.taskDescription|raw  }}
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}